#!/bin/bash
sudo modprobe -r lp
sudo chmod 777 /dev/parport0
sudo chmod 777 /dev/ttyACM0
read -p "subjectID: " subID
read -p "group: " group
read -p "[s] stroop, [e] EOG calibration, [t] training, or [d] decoding? " mode
read -p "would you like to watch the tutorial? [y] or [n] " tutorial
if [ "$mode"] != "e" ]; then
	read -p "would you like to practice? [y] or [n] " practice
fi

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )" #${BASH_SOURCE[0]} finds path to currently executing script and >/dev/null discards any output from cd

echo $dir

#########################################################################

if [ "$mode" = "e" ]
	then
 	echo "
----------------------------------
----> EOG Calibration Mode selected <-----
----------------------------------
"
	if [ "$tutorial" = "y" ]
	then
		tutorial_again="y"
		while [ "$tutorial_again" = "y" ]; do
		sleep 3
		vlc --play-and-exit --fullscreen --no-video-title-show "$dir/instructions/EOG_final.mp4"

		read -p "would you like to watch the tutorial again? [y] or [n] " tutorial_again
		done
	fi

# Open GDF and log files
datetime=$(date +%Y%m%d%H%M%S)
basename=$dir/data/"e"$subID"_"$datetime"_EOGcalibration"
foldername=$dir/data/"e"$subID"_"$(date +%Y%m%d) 
gdffilename=$basename".gdf"
logfilename=$basename".log"

mkdir $basename/

echo $gdffilename
echo $logfilename
cl_rpc openxdf $gdffilename $logfilename ""

sleep 3
python3 ./visualInterface/EOGcalibration.py "$basename"

# Close the GDF file
sleep 3
cl_rpc closexdf
mv $basename.* $basename/

mkdir -p $foldername
mv $basename $foldername


#########################################################################
elif [ "$mode" = "t" ]
 	then
 	echo "
----------------------------------
----> Training Mode selected <-----
----------------------------------
"
	if [ "$tutorial" = "y" ]
	then
		tutorial_again="y"
		while [ "$tutorial_again" = "y" ]; do
		sleep 3
		vlc --play-and-exit --fullscreen --no-video-title-show "$dir/instructions/DistractorTask_final.mp4"

		read -p "would you like to watch the tutorial again? [y] or [n] " tutorial_again
		done
	fi
# Open GDF and log files
datetime=$(date +%Y%m%d%H%M%S)
if [ "$practice" = "y" ]; then
	basename=$dir/data/"e"$subID"_"$datetime"_training_practice"
else 
	basename=$dir/data/"e"$subID"_"$datetime"_training"
fi
foldername=$dir/data/"e"$subID"_"$(date +%Y%m%d) 
gdffilename=$basename".gdf"
logfilename=$basename".log"

mkdir $basename/

echo $gdffilename
echo $logfilename
cl_rpc openxdf $gdffilename $logfilename ""

# Run Python Interface
sleep 3
python3 ./visualInterface/Pd_main.py "$basename" "train"

# Close the GDF file
sleep 3
cl_rpc closexdf
mv $basename.* $basename/

mkdir -p $foldername
mv $basename $foldername


#########################################################################

elif [ "$mode" = "d" ]
	then
 	echo "
----------------------------------
----> Decoding Mode selected <-----
----------------------------------
"
	if [ "$tutorial" = "y" ]
	then
		tutorial_again="y"
		while [ "$tutorial_again" = "y" ]; do
		sleep 3
		if [ "$group" = "51" ]
			then
			vlc --play-and-exit --fullscreen --no-video-title-show "$dir/instructions/BCI_final_51.mp4"
		elif [ "$group" = "93" ]
			then
			vlc --play-and-exit --fullscreen --no-video-title-show "$dir/instructions/BCI_final_93.mp4"	
		fi
		read -p "would you like to watch the tutorial again? [y] or [n] " tutorial_again
		done
	fi
echo "----- Operating points for decoding, e.g. 0.5 (Enter = keep previous) -----"
read -p "thrR (decoderR): " thrR
read -p "thrL (decoderL): " thrL
read -p "thrN (decoderN): " thrN
read -p "margin (ambivalence band): " margin

# Open GDF and log files
datetime=$(date +%Y%m%d%H%M%S)
if [ "$practice" = "y" ]; then
	basename=$dir/data/"e"$subID"_"$datetime"_decoding_practice"
else 
	basename=$dir/data/"e"$subID"_"$datetime"_decoding"
fi
foldername=$dir/data/"e"$subID"_"$(date +%Y%m%d) 
gdffilename=$basename".gdf"
logfilename=$basename".log"

mkdir $basename/

echo $gdffilename
echo $logfilename
cl_rpc openxdf $gdffilename $logfilename ""

# Run ndf file
sleep 2

gnome-terminal --title "Distractor Detection" -- bash -c "./matlabLauncher '$subID' '$thrR' '$thrL' '$thrN' '$margin'; echo 'Press Enter to close...'; read"

# Run python script
sleep 20
if [ "$group" = "51" ]
	then
	python3 ./visualInterface/Pd_main.py "$basename" "decode"
elif [ "$group" = "93" ]
	then
	python3 ./visualInterface/Pd_main.py "$basename" "decode_ctrl"
fi


# Close the GDF file
sleep 3
cl_rpc closexdf
mv $basename.* $basename/

mkdir -p $foldername
mv $basename $foldername

#########################################################################

elif [ "$mode" = "s" ]
	then
 	echo "
----------------------------------
----> Stroop Mode selected <-----
----------------------------------
"
	if [ "$tutorial" = "y" ]
	then
		tutorial_again="y"
		while [ "$tutorial_again" = "y" ]; do
		sleep 3
		vlc --play-and-exit --fullscreen --no-video-title-show "$dir/instructions/Stroop_final.mp4"

		read -p "would you like to watch the tutorial again? [y] or [n] " tutorial_again
		done
	fi
# Open GDF and log files
datetime=$(date +%Y%m%d%H%M%S)
if [ "$practice" = "y" ]; then
	basename=$dir/data/"e"$subID"_"$datetime"_stroop_practice"
else 
	basename=$dir/data/"e"$subID"_"$datetime"_stroop"
fi
foldername=$dir/data/"e"$subID"_"$(date +%Y%m%d) 
gdffilename=$basename".gdf"
logfilename=$basename".log"

mkdir $basename/

echo $gdffilename
echo $logfilename
cl_rpc openxdf $gdffilename $logfilename ""

sleep 3
python3 ./visualInterface/Stroop.py "$basename"

# Close the GDF file
sleep 3
cl_rpc closexdf
mv $basename.* $basename/

mkdir -p $foldername
mv $basename $foldername


fi #ends the if statement 